## Data 결합

In [67]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [68]:
ar1=np.arange(4)
ar1

array([0, 1, 2, 3])

In [69]:
ar1=np.arange(4),reshape(2,2)

NameError: name 'reshape' is not defined

In [70]:
ar1

array([0, 1, 2, 3])

In [75]:
np.concatenate([ar1,ar1], axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [90]:
df1=DataFrame({
    'A':[1,2,3],
    'B':[4,5,6],
})

In [91]:
df1

A  B
0  1  4
1  2  5
2  3  6

In [78]:
df2=DataFrame({
    'A':[10,11],
    'B':[40,50]
})

In [79]:
df2

A   B
0  10  40
1  11  50

In [87]:
df3=DataFrame({
    'A':[40,50, 60],
    'B':[70,80, 90],
    'C':[10,11,12]
})

In [88]:
df3

A   B   C
0  40  70  10
1  50  80  11
2  60  90  12

In [92]:
pd.concat([df1, df2, df3])

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


A   B     C
0   1   4   NaN
1   2   5   NaN
2   3   6   NaN
0  10  40   NaN
1  11  50   NaN
0  40  70  10.0
1  50  80  11.0
2  60  90  12.0

In [94]:
pd.concat([df1, df2], axis=1)

A  B     A     B
0  1  4  10.0  40.0
1  2  5  11.0  50.0
2  3  6   NaN   NaN

In [100]:
pd.concat([df1, df2], axis=1, join='outer')

A  B     A     B
0  1  4  10.0  40.0
1  2  5  11.0  50.0
2  3  6   NaN   NaN

In [110]:
A=pd.concat([df1, df2], axis=1, join='inner', keys=['ONE', 'TWO'])

In [112]:
A

ONE    TWO    
    A  B   A   B
0   1  4  10  40
1   2  5  11  50

In [114]:
B=pd.concat([df1, df2], axis=1, join='inner', keys=['ONE', 'TWO'])

In [116]:
B

ONE    TWO    
    A  B   A   B
0   1  4  10  40
1   2  5  11  50

In [120]:
df1= DataFrame({'A':[1,2,3,4], 'B':[5,6,7,8], 'C':[9,10,11,12]})

In [121]:
df1

A  B   C
0  1  5   9
1  2  6  10
2  3  7  11
3  4  8  12

In [123]:
df2 = DataFrame({'A':[a,b,c,d], 'B':[e,f,g,h], 'C':[i,j,k,l]})

NameError: name 'c' is not defined

In [124]:
df2

A   B
0  10  40
1  11  50

In [7]:
list_1 =[1,2,3,4]

In [10]:
a=np.array(list_1)

In [12]:
a

array([1, 2, 3, 4])

In [17]:
b=np.array([[1,2,3],[4,5,6]])

In [20]:
print(b.shape)

(2, 3)


In [22]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
list=[
      [1,2,3], 
      [4,5,6], 
      [7,8,9]
]

In [26]:
arr = np.array(list)

In [28]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
a= arr[1:, 1:]
a

array([[5, 6],
       [8, 9]])

In [32]:
# a=arr[0:, 2:]
a

array([[3],
       [6],
       [9]])

In [34]:
bool_array = np.array([
    [False, True, False],
    [True, False, True],
    [False, True, False]
])

In [36]:
bool_array

array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False]])

In [38]:
n=arr[bool_array]
n

array([2, 4, 6, 8])

In [43]:
# c=a-b
c=np.subtract(b,a)
print(c)

ValueError: operands could not be broadcast together with shapes (2,3) (3,1) 

In [45]:
c=np.multiply(a,b)
c

ValueError: operands could not be broadcast together with shapes (3,1) (2,3) 